name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install node modules
        run: npm ci 

      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            node_modules/
            src/
            Dockerfile
            package.json
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Run tests
        uses: npm run tests

  package:
    name: Package and upload
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: andersbea/ci-cd-github-to-gke:latest