name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        run: npm ci

      - name: Pack files
        run: |
          tar -cvf artifact.tar \
            node_modules/ \
            src/ \
            Dockerfile \
            package-lock.json \
            package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifact.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Unpack files and remove artifact
        run: (tar -xvf artifact/artifact.tar && rm -r artifact)

      - name: Run test
        run: npm test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: Unpack files and remove artifact
        run: (tar -xvf artifact/artifact.tar && rm -r artifact)

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/andersbea/ci-cd-github-to-gke:latest
