name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install node modules
        run: npm ci 

      - name: Run test
        run: npm run test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: andersbea/ci-cd-github-to-gke:latest
